export const environment = {
  production: false,
  apiUrl: 'https://aws-dev-01.isg.us/api',
  token: '/token',
  providers: '/republic/providers/filter',
  classTypes: '/republic/class_types/filter',
  products: '/republic/products/filter',
  service_lines: '/republic/config/service_lines',
  getCustomer: '/republic/customers/filter',
  putOrder: '/republic/orders',
  register: '/republic/customers',
  dish: '/republic/config/republic_wireless_url',
  email: 'admin@isg.us',
  password: 'admin@isg',
  dni_call: '/isg/dni_call_key_mapping/filter',
  sales_customer: '/sales/search/customers',
};