export const offerTaskIdName = "offerSelectConfigTask"
export const customerDetailsTaskName = "customerDetailsTask"
export const creditCheckTaskName = "creditCheckTask"
export const numberPortabilityTaskName = "numberPortabilityTask"
export const quoteValidationTaskName = "validateProductConfigurationTask"
export const posIdHoldTaskName = "posIdHoldTask"
export const reserveTaskName = "reserveScheduleTaskId"
